function net = train_drn(XTrain,YTrain,XValidation,YValidation,params)
%TRAIN_DRN Train the proposed deep residual learning-based estimator.
inputSize = size(XTrain,2);
outputSize = size(YTrain,2);
lgraph = build_drn(inputSize,outputSize);
options = trainingOptions('adam', ...
    'InitialLearnRate',params.training.initialLearnRate, ...
    'MaxEpochs',params.training.maxEpochs, ...
    'MiniBatchSize',params.training.miniBatchSize, ...
    'Shuffle','every-epoch', ...
    'GradientThreshold',params.training.gradientThreshold, ...
    'L2Regularization',params.training.l2Regularization, ...
    'LearnRateSchedule','piecewise', ...
    'LearnRateDropPeriod',params.training.learnRateDropPeriod, ...
    'LearnRateDropFactor',params.training.learnRateDropFactor, ...
    'ValidationData',{XValidation,YValidation}, ...
    'ValidationPatience',params.training.validationPatience, ...
    'Verbose',true, ...
    'Plots','none', ...
    'ExecutionEnvironment','auto');
net = trainNetwork(XTrain,YTrain,lgraph,options);
end
