function net = train_cnn(XTrain,YTrain,XValidation,YValidation,params)
%TRAIN_CNN Train the CNN benchmark with Adam and scheduled learning-rate decay.
inputSize = size(XTrain,2);
outputSize = size(YTrain,2);
layers = build_cnn(inputSize,outputSize);
options = trainingOptions('adam', ...
    'InitialLearnRate',params.training.initialLearnRate, ...
    'MaxEpochs',params.training.maxEpochs, ...
    'MiniBatchSize',params.training.miniBatchSize, ...
    'Shuffle','every-epoch', ...
    'GradientThreshold',params.training.gradientThreshold, ...
    'L2Regularization',params.training.l2Regularization, ...
    'LearnRateSchedule','piecewise', ...
    'LearnRateDropPeriod',params.training.learnRateDropPeriod, ...
    'LearnRateDropFactor',params.training.learnRateDropFactor, ...
    'ValidationData',{local_cnn_cells(XValidation),YValidation}, ...
    'ValidationPatience',params.training.validationPatience, ...
    'Verbose',true, ...
    'Plots','none', ...
    'ExecutionEnvironment','auto');
net = trainNetwork(local_cnn_cells(XTrain),YTrain,layers,options);
end

function C = local_cnn_cells(X)
C = cell(size(X,1),1);
for i=1:size(X,1)
    C{i} = reshape(X(i,:),1,[]);
end
end
